image: node:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
  - node_modules/

stages:
  - build
  - test

build:
  script:
   - npm install
   - npx tsc

test_harness:
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/harness/**/*.js"

test_annexB:
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/annexB/**/*.js"

test_builtins:
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/built-ins/**/*.js"

test_builtins:
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/intl402/**/*.js"

test_language:
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/language/**/*.js"
