image: node:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
  - node_modules/

stages:
  - build
  - test

build:
  stage: build
  script:
   - npm install
   - npx tsc
  artifacts:
    untracked: true
    when: on_success

test_custom:
  stage: test
  script:
   - npm run start
  variables:
    TEST_GLOB: "testCode/**/*.js"

test_harness:
  stage: test
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/harness/**/*.js"

test_annexB:
  stage: test
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/annexB/**/*.js"

test_builtins:
  stage: test
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/built-ins/**/*.js"

test_intl402:
  stage: test
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/intl402/**/*.js"

test_language:
  stage: test
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/language/**/*.js"
