image: node:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

build:
  stage: build
  script:
   - npm install
   - npx tsc
  cache:
    paths:
     - node_modules/
  artifacts:
    untracked: true
    when: on_success

test_custom:
  stage: test
  script:
   - npm run start
  variables:
    TESTS_GLOB: "testCode/**/*.js"

test_harness:
  stage: test
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/harness/**/*.js"

test_annexB:
  stage: test
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/annexB/**/*.js"

test_builtins:
  stage: test
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/built-ins/**/*.js"

test_intl402:
  stage: test
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/intl402/**/*.js"

test_language_arguments_object:
  stage: test
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/language/arguments-object/**/*.js"

test_language_asi:
  stage: test
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/language/asi/**/*.js"

test_language_block_scope:
  stage: test
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/language/block-scope/**/*.js"

test_language_comments:
  stage: test
  script:
   - npm run start
  variables:
    TESTS_GLOB: "test262/test/language/comments/**/*.js"


